### ISSUE TITLE
ZETA minting

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#643] opened 2023-05-23 13:55 UTC
Check supply on zetachain;
Check supply on external chains if possible.
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/878
- [ ] https://github.com/zeta-chain/node/issues/881
```

**Comment by lumtis** [comment] 2023-11-02 21:59
Closing as duplicate of https://github.com/zeta-chain/node/issues/564

**Closed by lumtis** 2023-11-02 21:59 UTC
