### ISSUE TITLE
Can't send tokens/stake using the Leap wallet

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#1230] opened 2023-10-03 17:55 UTC
<img width="396" alt="Screenshot 2023-09-20 at 13 19 11" src="https://github.com/leapwallet/cosmos-extension/assets/332151/058cf840-484c-4b4f-8462-b006ade014f4">

May be related to these queries to the `txs` endpoint.

<img width="1473" alt="Screenshot 2023-09-20 at 13 26 35" src="https://github.com/leapwallet/cosmos-extension/assets/332151/5d6ee362-7fc7-4429-9983-cfb059d9459a">

<img width="1473" alt="Screenshot 2023-09-20 at 13 26 37" src="https://github.com/leapwallet/cosmos-extension/assets/332151/6980fc82-a5f5-441e-8c87-e7d5e17c9ef4">

Claiming staking rewards also fails.

<img width="396" alt="Screenshot 2023-09-20 at 13 24 23" src="https://github.com/leapwallet/cosmos-extension/assets/332151/1e65b28a-97df-4fd1-9e45-250890fd4de1">

**Comment by lumtis** [comment] 2023-10-05 21:49
Not sure what can be the cause, I may think we don't have customization for transfer and staking.

Could it be infra related? @zeta-chain/devops

**Comment by lumtis** [comment] 2023-10-25 17:37
@fadeev is it still relevant to keep this issue and https://github.com/zeta-chain/node/issues/1231 in `node` backlog?

**Comment by fadeev** [comment] 2023-10-28 12:55
@lumtis yes, I believe it is relevant. It's still broken and given that both wallets stopped working at the same time suggests it might be something with the `node`.

**Comment by ws4charlie** [comment] 2023-12-19 22:01
Leap wallet works well now. I think we can close this issue.
![image](https://github.com/zeta-chain/node/assets/34498985/6c158650-ff1a-401c-9e8b-3a56b3116fba)

**Closed by ws4charlie** 2023-12-19 22:01 UTC
Labels: bug
